# Use the specific Moonraker image as the base
FROM mkuf/moonraker:v0.9.3-3-gccfe32f

USER root

# Install ffmpeg and clean up the APT cache
# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get install -y --no-install-recommends ffmpeg && \
    rm -rf /var/lib/apt/lists/*

USER moonraker

# Ensure the default entrypoint and CMD are preserved
ENTRYPOINT ["/opt/venv/bin/python", "moonraker/moonraker/moonraker.py"]
CMD ["-d", "/opt/printer_data"]
