services:
  klipper:
    build:
      context: .
      dockerfile: Dockerfile-klipper
    restart: unless-stopped
    container_name: klipper
    privileged: true
    volumes:
      - /dev:/dev
      - ./config:/home/klipper/config
      - ./KlipperMaintenance/maintain.py:/home/klipper/klipper/klippy/extras/maintain.py
      #- ./chopper-resonance-tuner/gcode_shell_command.py:/klipper/klippy/extras/gcode_shell_command.py
      #- ./chopper-resonance-tuner:/home/klippy/chopper-resonance-tuner

  moonraker:
    build:
      context: .
      dockerfile: Dockerfile-moonraker
    restart: unless-stopped
    container_name: moonraker
    pid: host
    ports:
      - "7125:7125"
    volumes:
      - /run/systemd:/run/systemd
      - /run/dbus:/run/dbus
      - ./database:/opt/printer_data/database
      - ./config:/opt/printer_data/config
      #- /dev/null:/opt/klipper/config/null
      #- /dev/null:/opt/klipper/docs/null
      #- ./gcodes:/opt/printer_data/gcodes
      #- ./logs:/opt/printer_data/logs
      #- ./timelapse:/opt/printer_data/timelapse
      #- ./moonraker-timelapse/component/timelapse.py:/opt/moonraker/moonraker/components/timelapse.py

  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true