FROM ubuntu:22.04

USER root

ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies and set up environment
RUN rm -rf /var/lib/apt/lists/* /tmp/apt-dpkg-install-* && apt-get clean && \
    apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends sudo git curl zlib1g-dev libjpeg-dev libfreetype6-dev libatlas-base-dev libopenblas-dev

RUN useradd -ms /bin/bash klipper && adduser klipper dialout
RUN mkdir /home/klipper/config
VOLUME /home/klipper/config

WORKDIR /home/klipper

# Download and install Klipper
# Use a specific fork if needed, otherwise use the main Klipper repository
# Uncomment the next line to use the main Klipper repository
# ARG GITHUB_FORK_URL=
ARG GITHUB_FORK_URL=https://github.com/jpcurti/ender3-v3-se-klipper-with-display.git
RUN git clone --depth=1 $GITHUB_FORK_URL /home/klipper/klipper

RUN echo 'klipper ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/klipper && \
    chown klipper:klipper -R /home/klipper && \
    ln -s /bin/true /bin/systemctl

#Shaketune download
RUN git clone https://github.com/Frix-x/klippain-shaketune.git

# Install dependencies
USER klipper
RUN /home/klipper/klipper/scripts/install-ubuntu-22.04.sh
RUN mkdir -p /home/klipper/klipper/klippy/extras/shaketune
RUN cp -r klippain-shaketune/shaketune /home/klipper/klipper/klippy/extras/
RUN /home/klipper/klippy-env/bin/pip install -r klippain-shaketune/requirements.txt  
RUN mkdir -p /home/klipper/printer_data && chown klipper:klipper /home/klipper/printer_data

# Run Klipper
CMD ["/home/klipper/klippy-env/bin/python", "/home/klipper/klipper/klippy/klippy.py", "/home/klipper/config/printer.cfg", "-a", "/home/klipper/config/klippy_uds"]
