FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends ffmpeg && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir requests

COPY print_watcher.py /print_watcher.py

CMD ["python", "/print_watcher.py"]
